x-environment: &environment
  WORDPRESS_DB_HOST: "database"
  WORDPRESS_DB_NAME: &WORDPRESS_DB_NAME "wordpress"
  WORDPRESS_DB_USER: &WORDPRESS_DB_USER "wordpress"
  WORDPRESS_DB_PASSWORD: &WORDPRESS_DB_PASSWORD "wordpress"
  MYSQL_DATABASE: *WORDPRESS_DB_NAME
  MYSQL_USER: *WORDPRESS_DB_USER
  MYSQL_PASSWORD: *WORDPRESS_DB_PASSWORD
  MYSQL_RANDOM_ROOT_PASSWORD: '1'

services:

  wordpress:
    image: wordpress
    restart: always
    expose:
      - "80"
    environment: *environment
    volumes:
      - wordpress:/var/www/html
    deploy:
      mode: replicated
      replicas: 3

  database:
    image: mysql:8.0
    restart: always
    environment: *environment
    volumes:
      - database:/var/lib/mysql

volumes:
  wordpress:
  database:
